---
require:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false

inherit_mode:
  merge:
    - AllowedNames

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - z

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
 
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

