---
require:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
